// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function() {
    /*
    	Enable fly-out menus in top nav.
    */

    var $flyOutParents, $flyoutContainer;
    $flyOutParents = $('.has-flyout-menu');
    $flyoutContainer = $('#flyout-container');
    return $flyOutParents.each(function(i, elm) {
      var $flyoutMenu;
      if (elm.getAttribute('data-submenu') !== null) {
        $flyoutMenu = $('.' + elm.getAttribute('data-submenu'));
      }
      $flyoutContainer.append($flyoutMenu);
      elm.onmouseover = function(e) {
        $flyoutMenu.show();
        return $(this).addClass('selected');
      };
      return $flyoutMenu.mouseleave(function(e) {
        $flyoutMenu.hide();
        return $(elm).removeClass('selected');
      });
    });
  });

}).call(this);
