// Generated by CoffeeScript 1.4.0

$(document).ready(function() {
  /*
  	Language switch mechanism
  */

  var $flyOutParents, $flyoutContainer, $imagesContainer, $imagesSponsors, $imagesWelcome, $langSwitch, $slideshowContainer, $sponsors, index, setLang, showImage, tick, timer;
  $langSwitch = $('.lang-switch');
  console.log($langSwitch);
  /*
  	Display proper language
  */

  setLang = function(lang) {
    if (lang === 'fr') {
      $('.en').css('display', 'none');
      $('.fr').css('display', 'block');
      $('.to-en', $langSwitch).removeClass('selected');
      return $('.to-fr', $langSwitch).addClass('selected');
    } else {
      $('.fr').css('display', 'none');
      $('.en').css('display', 'block');
      $('.to-fr', $langSwitch).removeClass('selected');
      return $('.to-en', $langSwitch).addClass('selected');
    }
  };
  /*
  	Enable fly-out menus in top nav.
  */

  $flyOutParents = $('.has-flyout-menu');
  $flyoutContainer = $('#flyout-container');
  $flyOutParents.each(function(i, elm) {
    var $flyoutMenu;
    if (elm.getAttribute('data-submenu') !== null) {
      $flyoutMenu = $('.' + elm.getAttribute('data-submenu'));
    }
    $flyoutContainer.append($flyoutMenu);
    elm.onmouseover = function(e) {
      $flyoutMenu.show();
      return $(this).addClass('selected');
    };
    return $flyoutMenu.mouseleave(function(e) {
      $flyoutMenu.hide();
      return $(elm).removeClass('selected');
    });
  });
  /*
  	Set default language.
  */

  setLang($('meta[name="current_lang"]').attr('content'));
  /*
  	Extend jQuery to check if a jQuery selector is empty.
  */

  $.fn.exists = function() {
    return this.length !== 0;
  };
  /*
  	Get images loaded in the "welcome" section of the homepage.
  */

  $imagesWelcome = $('#page-accueil .welcome img');
  if ($imagesWelcome.exists()) {
    $slideshowContainer = $('.slideshow');
    $imagesWelcome.each(function(i, img) {
      $(img).addClass('slide');
      return $slideshowContainer.append(img);
    });
    timer = 3000;
    index = 0;
    showImage = function(index) {
      return $imagesWelcome.each(function(i, img) {
        if (index === i) {
          return $(img).fadeIn(1000);
        } else {
          return $(img).fadeOut(1000);
        }
      });
    };
    tick = setInterval(function() {
      showImage(index);
      if (index < $imagesWelcome.length - 1) {
        return index++;
      } else {
        return index = 0;
      }
    }, timer);
  }
  /*
  	Get links (images, basically) loaded in the "sponsors" section of /presentation
  */

  $imagesSponsors = $('#page-presentation .sponsors a');
  if ($imagesSponsors.exists()) {
    $sponsors = $('.sponsors');
    $imagesContainer = $('.images');
    $imagesSponsors.each(function(i, img) {
      return $imagesContainer.append(img);
    });
    return $sponsors.append($imagesContainer);
  }
});
