// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function() {
    /*
    	Language switch mechanism
    */

    var $flyOutParents, $flyoutContainer, $langSwitch;
    $langSwitch = $('.lang-switch');
    $langSwitch.click(function(e) {
      return $.ajax({
        url: '/wp-admin/admin-ajax.php',
        data: {
          action: 'switch',
          lang: e.target.getAttribute('data-lang')
        },
        complete: function(xhr) {
          return console.log(xhr.responseText);
        }
      });
    });
    /*
    	Enable fly-out menus in top nav.
    */

    $flyOutParents = $('.has-flyout-menu');
    $flyoutContainer = $('#flyout-container');
    return $flyOutParents.each(function(i, elm) {
      var $flyoutMenu;
      if (elm.getAttribute('data-submenu') !== null) {
        $flyoutMenu = $('.' + elm.getAttribute('data-submenu'));
      }
      $flyoutContainer.append($flyoutMenu);
      elm.onmouseover = function(e) {
        $flyoutMenu.show();
        return $(this).addClass('selected');
      };
      return $flyoutMenu.mouseleave(function(e) {
        $flyoutMenu.hide();
        return $(elm).removeClass('selected');
      });
    });
  });

}).call(this);
